################################# Basic configuration #########################
# Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
baseURL = "https://ntropy-esa.github.io/biochar-systems/"
title = 'Biochar Systems'
theme = "airspace-hugo-adapted"
themesDir = 'themes'
buildDrafts = true # include draft pages when building, or not
publishDir = '../biochar-systems/' # default: 'public'
ignoreErrors = ["error-remote-getcsv"]

disablePathToLower = false # if true, do not convert the url/path to lowercase.
enableEmoji = true # Enable Emoji emoticons support for page content; see the Emoji Cheat Sheet. https://www.webfx.com/tools/emoji-cheat-sheet/
enableInlineShortcodes = true # Enable inline shortcode support for content pages. See Inline Shortcodes https://gohugo.io/templates/shortcode-templates/#inline-shortcodes

# Default time zone for time stamps; use any valid [tz database name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List)
timeZone = "UTC"
# Number of posts per page in list view
paginate = "4"
# Post excerpt length
summaryLength = "30"
# Disabled languages
disableLanguages = []
defaultContentLanguage = 'en' # Content without language indicator will default to this language.
defaultContentLanguageInSubdir = false # have content directory for 'en' rendered as well, if true

# Short name to enable Disqus comments
disqusShortname = "" # Get your shortname from here: https://disqus.com/profile/signup/
# Measurement ID (G-XXXXXXX) to enable Google Analytics
googleAnalytics = ""

############################# Modules ##############################
[module.hugoVersion]
extended = true
min = "0.87.0"


################################# Output formats ##############################
# Documentation: https://gohugo.io/templates/output-formats/#customizing-output-formats

[outputs]
home = [ "HTML" ]


################################# Markup ######################################
# Documentation: https://gohugo.io/getting-started/configuration-markup

[markup.goldmark.renderer]
# Allow "unsafe" HTML in Markdown
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 3
ordered = false


################################# Default parameters ##########################
[params]
	favicon = "img/favicon.png"
	logo = "img/logo.png"
	logo_sidetext = "Biochar Systems<br/>Research Group"
	logo_width = "50px"
	# OpenGraph / Twitter Card metadata
	description = "This is meta description"
	author = "Themefisher"
	image = "images/logo.png" # this image will be used as fallback if a page has no image of its own


################################# Sidebar widgets #############################
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


################################# Contact page ################################
[params.contact]
# Address block
phone = "0700193988"
email = "demo@email.com"
location = """
**Themefisher**  
North Main Street  
Brooklyn, New South Wales  
Australia
"""
# Whether to display text descriptors (like "E-mail: ", "Phone: ") before the address block elements
address_descriptors = false
[params.contact.form]
enable = false
# Whether to use [Netlify Forms](https://docs.netlify.com/forms/setup/)
use_netlify = false
# Form action
## Fill in your Form ID URL for Formspree.io, e.g. `https://formspree.io/f/{form_id}`
## Ignored if `use_netlify = true` (custom [success page](https://docs.netlify.com/forms/setup/#success-messages) is already included) 
action = "#"
# Image on custom success page `/message_sent.html`
success_image = "images/paper-plane.svg"


################################# Google map ##################################
[params.gmap]
enable = true
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"


################################# Preloader ###################################
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif image


################################# Cookies #####################################
[params.cookies]
enable = false
expire_days = 2


################################# counter.dev analytics #######################
# This is a [privacy-friendly alternative](https://counter.dev/privacy.html) to Google Analytics & Co.
[params.counter]
enable = true
# counter.dev username, see https://counter.dev/setup.html
username = ""


################################# Social Media ################################
[[params.social]]
icon = "ion-social-googleplus-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-pinterest-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-dribbble-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"


################################# Plugins #####################################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/css/bootstrap.min.css"
attributes = "media='screen'"

[[params.plugins.css]]
link = "plugins/ionicons/css/ionicons.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/slick/slick.css"
attributes = ""

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/bootstrap/js/bootstrap.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
attributes = "defer"

################################# English translation #########################
[languages.en]
	languageName = "English"
	languageCode = "en-en"
	contentDir = "content/en"
	weight = 1
	title = 'Biochar Systems'
	copyright = 'Elias S. Azzi, Cecilia Sundberg, KTH, SLU'

	# Navigation menus
	# NOTE: Leaf entries linking to content should be defined in the content file's respective front matter.
	[[languages.en.menu.main]]
		hasChildren = true
		name = "Systems analysis"
		weight = 2

	[[languages.en.menu.main]]
		hasChildren = true
		name = "Case studies"
		weight = 3

	[[languages.en.menu.main]]
		hasChildren = true
		name = "More"
		weight = 5

################################# Swedish translation ##########################
[languages.sv]
	languageName = "Swedish"
	languageCode = "se-se"
	contentDir = "content/sv"
	weight = 2
	title = 'Biokolsystem'
	copyright = 'Elias S. Azzi, Cecilia Sundberg, KTH, SLU'

	# Navigation menus
	# NOTE: Leaf entries linking to content should be defined in the content file's respective front matter.
	[[languages.sv.menu.main]]
		hasChildren = true
		name = "Systemanalysis"
		weight = 2

	[[languages.sv.menu.main]]
		hasChildren = true
		name = "Fallstudier"
		weight = 3

	[[languages.sv.menu.main]]
		hasChildren = true
		name = "Mer"
		weight = 5		